name: interview_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.10.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Firebase (Auth only)
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  
  # State Management
  flutter_riverpod: ^2.6.1
  
  # Local Database
  isar_community: ^3.3.0
  isar_community_flutter_libs: ^3.3.0
  
  # File Handling & Storage
  file_picker: ^8.1.6
  path_provider: ^2.1.5
  
  # PDF
  syncfusion_flutter_pdf: ^28.2.12
  syncfusion_flutter_pdfviewer: ^28.1.33
  
  # Signature
  signature: ^6.3.0
  
  # JSON
  json_annotation: ^4.9.0
  
  # UI
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1
  equatable: ^2.0.7
  dartz: ^0.10.1
  intl: ^0.20.2
  share_plus: ^12.0.1
  image_picker: ^1.2.1
  pdf_image_renderer: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Code Generators
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  isar_community_generator: ^3.3.0


flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: Cursive
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf
          weight: 400
